"""create transaction and decision tables

Revision ID: 26647400a765
Revises:
Create Date: 2026-09-11 01:51:13.347552

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "26647400a765"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.String(length=64), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("card_token", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("ip_token", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("card_present", sa.Boolean(), nullable=False),
        sa.Column("authentication_result", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_transactions_amount_positive")),
        sa.CheckConstraint("card_present = false", name=op.f("ck_transactions_card_not_present")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_index(
        "ix_transactions_account_event_time",
        "transactions",
        ["account_id", "event_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_account_id"), "transactions", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_card_token"), "transactions", ["card_token"], unique=False
    )
    op.create_index(
        "ix_transactions_device_event_time",
        "transactions",
        ["device_id", "event_time"],
        unique=False,
    )
    op.create_index(op.f("ix_transactions_device_id"), "transactions", ["device_id"], unique=False)
    op.create_index(
        op.f("ix_transactions_event_time"), "transactions", ["event_time"], unique=False
    )
    op.create_index(
        "ix_transactions_ip_event_time", "transactions", ["ip_token", "event_time"], unique=False
    )
    op.create_index(op.f("ix_transactions_ip_token"), "transactions", ["ip_token"], unique=False)
    op.create_index(
        op.f("ix_transactions_merchant_id"), "transactions", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_transaction_id"), "transactions", ["transaction_id"], unique=True
    )
    op.create_table(
        "decision_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transaction_record_id", sa.Uuid(), nullable=False),
        sa.Column("fraud_probability", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("triggered_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("component_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("rules_version", sa.String(length=64), nullable=False),
        sa.Column("decision_policy_version", sa.String(length=64), nullable=False),
        sa.Column("feature_freshness_ms", sa.Integer(), nullable=False),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('APPROVE', 'REVIEW', 'DECLINE')",
            name=op.f("ck_decision_events_decision_allowed"),
        ),
        sa.CheckConstraint(
            "feature_freshness_ms >= 0",
            name=op.f("ck_decision_events_feature_freshness_nonnegative"),
        ),
        sa.CheckConstraint(
            "fraud_probability >= 0 AND fraud_probability <= 1",
            name=op.f("ck_decision_events_fraud_probability_range"),
        ),
        sa.CheckConstraint("latency_ms >= 0", name=op.f("ck_decision_events_latency_nonnegative")),
        sa.CheckConstraint(
            "risk_score >= 0 AND risk_score <= 1000",
            name=op.f("ck_decision_events_risk_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_record_id"],
            ["transactions.id"],
            name=op.f("fk_decision_events_transaction_record_id_transactions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_events")),
    )
    op.create_index(
        "ix_decision_events_decision_scored_at",
        "decision_events",
        ["decision", "scored_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_events_transaction_record_id"),
        "decision_events",
        ["transaction_record_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_events_transaction_scored_at",
        "decision_events",
        ["transaction_record_id", "scored_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_decision_events_transaction_scored_at", table_name="decision_events")
    op.drop_index(op.f("ix_decision_events_transaction_record_id"), table_name="decision_events")
    op.drop_index("ix_decision_events_decision_scored_at", table_name="decision_events")
    op.drop_table("decision_events")
    op.drop_index(op.f("ix_transactions_transaction_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_merchant_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_ip_token"), table_name="transactions")
    op.drop_index("ix_transactions_ip_event_time", table_name="transactions")
    op.drop_index(op.f("ix_transactions_event_time"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_device_id"), table_name="transactions")
    op.drop_index("ix_transactions_device_event_time", table_name="transactions")
    op.drop_index(op.f("ix_transactions_card_token"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_account_id"), table_name="transactions")
    op.drop_index("ix_transactions_account_event_time", table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
